require:
  - rubocop-performance
  - rubocop-rspec

Layout/AlignHash:
  EnforcedHashRocketStyle: table

Metrics/LineLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/link-header-parser.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
