require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - spec/support/**/*.rb

Naming/FileName:
  Exclude:
    - lib/link-header-parser.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
