require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/link-header-parser.rb
