inherit_from:
  - https://github.com/jgarber623/rubocop-configs/raw/main/.rubocop.yml
  - https://github.com/jgarber623/rubocop-configs/raw/main/.rubocop-rspec.yml

require:
  - rubocop-packaging

AllCops:
  TargetRubyVersion: "3.0"

Naming/FileName:
  Exclude:
    - lib/link-header-parser.rb
