name: Publish

on:
  release:
    types: [published]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
  publish-to-rubygems:
    name: Publish to RubyGems
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${{ secrets.RUBYGEMS_TOKEN }}\n" > $HOME/.gem/credentials
      - run: bundle exec rake release
  publish-to-github-packages:
    name: Publish to GitHub Packages
    permissions:
      contents: read
      packages: write
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${{ secrets.GITHUB_TOKEN }}\n" > $HOME/.gem/credentials
      - run: bundle exec rake release
        env:
          BUNDLE_GEM__PUSH_KEY: github
          RUBYGEMS_HOST: "https://rubygems.pkg.github.com/${{ github.repository_owner }}"
